# Generated by Django 2.2.3 on 2019-08-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWorld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_role',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
